Origin 1
Moon-River-Web3/sfl-notifier pull request #4
Opened 2023-09-23 00:44 UTC by iga-marty

Пересобранная работающая версия бота (без функции уведомлений).
Все кнопки работают, подписи отображаются верно.
Полностью переписан main и файл sqlite_database.py - обращение к базе теперь производится через orm (peewee).

2023-09-25 20:29 UTC, AzaroQL requested changes

2023-09-25 20:29 UTC, AzaroQL commented on main.py
> +load_dotenv(find_dotenv())
Тут точно надо внутри вызывать find_dotenv() ?

2023-09-25 20:29 UTC, AzaroQL commented on main.py
> +	if (sqlite_database.create_user(message.chat.id) or
Ты на строчку выше сохранил значение в переменную с коротким названием, используй ее

2023-09-25 20:29 UTC, AzaroQL commented on sqlite_database.py
> +	).where(User.user_id == chat_id).execute()
Какието странные переносы у тебя тут, оно же не читается нормально

```
User \
  .update({User.wallet_number: new_wallet_number}) \
  .where(User.user_id == chat_id) \
  .execute()
```
  
попробуй так

2023-09-25 20:29 UTC, AzaroQL commented on web_3.py
> +alchemy_url = 'https://polygon-mainnet.g.alchemy.com/v2/nEzHYxo-SYWcxLZAr98fMOdRk6K-Q1Hs'
это же надо в .env файл, норм ключ спалил)

2023-09-26 13:06 UTC, iga-marty commented on sqlite_database.py
> +	).where(User.user_id == chat_id).execute()
Согласно pep8, мой вариант переноса предпочтительней, хоть и неидеально выглядит. Подумаю, как улучшить

2023-09-26 13:09 UTC, iga-marty commented on main.py
> +load_dotenv(find_dotenv())
![image](https://github.com/Moon-River-Web3/sfl-notifier/assets/136918698/ded66770-ca20-4c50-98e3-f5c9f01eb7aa)

2023-09-26 13:09 UTC, iga-marty commented on main.py
> +load_dotenv(find_dotenv())
Работает же)

2023-09-26 13:56 UTC, AzaroQL approved these changes

2023-09-26 13:58 UTC, merged